/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#fbaee9',
        'surface-variant': '#e8e0eb',
        'inverse-on-surface': '#f7eef9',
        'secondary-fixed-dim': '#b8d074',
        'on-primary-fixed-variant': '#6c3063',
        'primary-fixed-dim': '#fbaee9',
        'secondary': '#526615',
        'surface-tint': '#88487c',
        'primary': '#260023',
        'surface-bright': '#fff7ff',
        'tertiary': '#0a1300',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#b9ce91',
        'tertiary-fixed': '#d5ebaa',
        'tertiary-container': '#1b2a00',
        'inverse-surface': '#332f37',
        'outline': '#81737c',
        'surface-dim': '#e0d7e3',
        'outline-variant': '#d3c2cc',
        'error': '#ba1a1a',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#3b4d00',
        'background': '#fff7ff',
        'surface': '#fff7ff',
        'primary-fixed': '#ffd7f2',
        'error-container': '#ffdad6',
        'on-secondary-container': '#586c1b',
        'on-surface-variant': '#50434b',
        'on-secondary': '#ffffff',
        'on-primary-container': '#bc75ad',
        'on-tertiary-container': '#80945c',
        'on-error': '#ffffff',
        'secondary-container': '#d4ed8d',
        'surface-container': '#f4ebf7',
        'surface-container-high': '#eee5f1',
        'on-tertiary-fixed-variant': '#3b4c1c',
        'on-tertiary-fixed': '#131f00',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#390134',
        'on-surface': '#1e1a22',
        'on-secondary-fixed': '#161f00',
        'secondary-fixed': '#d4ed8d',
        'primary-container': '#450c3f',
        'surface-container-low': '#faf1fc',
        'surface-container-highest': '#e8e0eb',
        'on-background': '#1e1a22',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '1.5rem',
        'margin-mobile': '1rem',
        'space-xl': '2.5rem',
        'space-md': '1rem',
        'margin': '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        'gutter-mobile': '1rem',
      },
      fontFamily: {
        'title-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Hanken Grotesk', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'display-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'title-sm': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'display': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
